name: calender
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.3
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  dio: ^5.4.1
  google_fonts: ^5.1.0
  flutter_rating_bar: ^4.0.0
  image_picker: ^1.0.7
  animate_do: ^3.0.2
  connectivity_plus: ^6.0.2
  flutter_toggle_tab: ^1.4.1
  persistent_bottom_nav_bar: ^5.0.2
  get_storage: ^2.1.1
  dropdown_model_list: ^2.1.1
  flutter_local_notifications: ^17.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  intl: ^0.19.0
  http: ^1.2.1
  flutter_timezone: ^1.0.8
  device_info_plus: ^10.1.0


dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/icons/


  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700